name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # or master, depending on your default branch

permissions:
  contents: write # This is important!

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci # or bun install
        
      - name: Build
        run: npm run build # or bun run build
      
      - name: Debug dist directory
        run: ls -la dist/
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Remove this if you don't want to keep deployment history
          enable_jekyll: false
          keep_files: false
